graph TD

User[普通用户] --> UC1[浏览商品]
User --> UC2[选择商品数量]
User --> UC3[提交订单]
User --> UC4[查看订单记录]

Admin[管理员] --> UC5[添加商品]
Admin --> UC6[修改商品信息]
Admin --> UC7[删除商品]

Admin --> UC8[添加商品种类]
Admin --> UC9[修改商品种类]
Admin --> UC10[删除商品种类]

Admin --> UC11[添加生产商]
Admin --> UC12[修改生产商]
Admin --> UC13[删除生产商]

Admin --> UC14[添加用户账号]
Admin --> UC15[修改用户账号]
Admin --> UC16[删除用户账号]
